#! /bin/sh

sxhkd &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true

# Automatic insertion/split settings
# (longest_side should be supported in a release after 0.9.5, already in Git)
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config split_ratio 0.5

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#9FBC00"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"
