#!/usr/bin/env bash

LAUNCHER="rofi -show drun -modi drun -show-icons"
LOCK_SCREEN=i3lock

#=======================================================================
# Startup / reset / reload
#=======================================================================

# Composer
pkill -u $USER -x 'compton'
compton &

# Herbstluft WM

# kill dangling clients (e.g., for the panel)
pkill -u $USER 'herbstclient'

# short alias
hc() {
    herbstclient "$@"
}

hc emit_hook reload
hc keyunbind --all
hc mouseunbind --all
hc detect_monitors

#=======================================================================
# Key bindings
#=======================================================================

# Media
hc keybind XF86AudioLowerVolume  spawn amixer -q set Master 2%- unmute
hc keybind XF86AudioRaiseVolume  spawn amixer -q set Master 2%+ unmute
hc keybind XF86AudioMute         spawn amixer -q set Master mute

# Session management
hc keybind Alt-Control-l       spawn ${LOCK_SCREEN}
hc keybind Alt-Control-r       reload
hc keybind Alt-Control-Delete  quit

# Run/close
hc keybind Super-w       close_or_remove
hc keybind Super-Return  spawn ${LAUNCHER}

# Focusing clients
hc keybind Super-h focus  left
hc keybind Super-j focus  down
hc keybind Super-k focus  up
hc keybind Super-l focus  right

# Moving clients
hc keybind Super-Shift-h  shift left
hc keybind Super-Shift-j  shift down
hc keybind Super-Shift-k  shift up
hc keybind Super-Shift-l  shift right

# Splitting frames
hc keybind Super-u  split bottom  0.5
hc keybind Super-o  split right   0.5
hc keybind Super-e  split explode

# Resizing frames
resizestep=0.05
hc keybind Super-Control-h  resize left +$resizestep
hc keybind Super-Control-j  resize down +$resizestep
hc keybind Super-Control-k  resize up +$resizestep
hc keybind Super-Control-l  resize right +$resizestep

# Tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "Super-$key" use_index "$i"
        hc keybind "Super-Shift-$key" move_index "$i"
    fi
done

# Cycle through tags
hc keybind Super-period use_index +1 --skip-visible
hc keybind Super-comma  use_index -1 --skip-visible

# Layouting
hc keybind Super-Shift-p  pseudotile toggle
hc keybind Super-space    cycle_layout +1 vertical horizontal
hc keybind Super-s        floating toggle
hc keybind Super-f        fullscreen toggle
hc keybind Super-m        set_layout max
hc keybind Super-g        set_layout grid

# Mouse
hc mousebind Super-Button1 move
hc mousebind Super-Button2 zoom
hc mousebind Super-Button3 resize

# Focus
hc keybind Super-Tab        cycle +1
hc keybind Super-Shift-Tab  cycle -1
hc keybind Alt-Tab          cycle_all +1
hc keybind Alt-Shift-Tab    cycle_all -1

#=======================================================================
# Theme and WM settings
#=======================================================================

xsetroot -solid '#222222' # fallback if no wallpaper
feh --bg-scale $HOME/Pictures/wallpaper.png

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#9fbc00'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 12

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

hc set focus_follows_mouse 1
hc set tree_style '╾│ ├└╼─┐'

#=======================================================================
# Rules
#=======================================================================

hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

#=======================================================================
# Panel
#=======================================================================

# 18px matches the polybar config height
hc pad 0 18 

pkill -u $USER 'polybar'
polybar 'top' &

#=======================================================================
# Finalize / Redraw all
#=======================================================================

hc unlock
