#!/usr/bin/env bash

COMPOSITOR=picom
LAUNCHER="rofi -dpi 1 -show drun -modi drun -show-icons"
WINDOW_FIND="rofi -dpi 1 -show window -modi window -show-icons"
LOCK_SCREEN=$(dirname "$0")/lock
BROWSER=firefox
FILES=nemo
TERMINAL=xfce4-terminal
CALCULATOR="rofi -dpi 1 -show calc -modi calc -no-show-match -no-sort"

COLOR_ACTIVE='#9fbc00'
COLOR_NORMAL='#565656'
BORDER_WIDTH=4

#=======================================================================
# Startup / reset / reload
#=======================================================================

# Compositor
pkill -u $USER -x $COMPOSITOR
$COMPOSITOR &

# Per-client keyboard layout switcher
pkill -u $USER --full hlwm_perclient_kb_layout
$(dirname "$0")/hlwm_perclient_kb_layout &

# Herbstluft WM

# kill dangling clients (e.g., for the panel)
pkill -u $USER 'herbstclient'

# short alias
hc() {
    herbstclient "$@"
}

hc emit_hook reload
hc keyunbind --all
hc mouseunbind --all

#=======================================================================
# Theme and WM settings
#=======================================================================

xsetroot -solid '#222222' # fallback if no wallpaper
feh --bg-scale $HOME/Pictures/wallpaper.{png,jpg}

hc attr settings.auto_detect_monitors true
hc attr settings.auto_detect_panels true
hc attr settings.focus_follows_mouse true
hc attr settings.tree_style "╾│ ├└╼─┐"

hc attr settings.default_frame_layout 2 # max

# Frame setup
hc attr settings.always_show_frame true
hc attr settings.frame_bg_active_color $COLOR_ACTIVE
hc attr settings.frame_bg_normal_color $COLOR_NORMAL
hc attr settings.frame_bg_transparent true
hc attr settings.frame_border_width 0
hc attr settings.frame_gap $BORDER_WIDTH
hc attr settings.frame_transparent_width $BORDER_WIDTH

# Do not hide surroundings even if no ambiguity
hc attr settings.smart_frame_surroundings false
hc attr settings.smart_window_surroundings false

# Resize window content immediately during resizing it with the mouse
hc attr settings.update_dragged_clients true

# Full-reset theme
hc attr theme.reset 1

# Setup theme
hc attr theme.border_width $BORDER_WIDTH
hc attr theme.floating.border_width $((BORDER_WIDTH / 2))

hc attr theme.color $COLOR_NORMAL
hc attr theme.active.color $COLOR_ACTIVE
hc attr theme.urgent.color '#fd4000'

#=======================================================================
# Key bindings
#=======================================================================

# For key names definitions see:
# https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h

# Media
hc keybind XF86AudioLowerVolume  spawn amixer -q set Master 2%- unmute
hc keybind XF86AudioRaiseVolume  spawn amixer -q set Master 2%+ unmute
hc keybind XF86AudioMute         spawn amixer -q set Master mute

# Session management
hc keybind Alt-Control-l       spawn ${LOCK_SCREEN}
hc keybind Alt-Control-r       reload
hc keybind Alt-Control-Delete  quit

# Run/close
hc keybind Super-q       close_or_remove
hc keybind Super-Return  spawn ${LAUNCHER}
hc keybind Super-slash   spawn ${WINDOW_FIND}
hc keybind Super-b       spawn ${BROWSER}
hc keybind Super-t       spawn ${TERMINAL}
hc keybind Super-f       spawn ${FILES}
hc keybind Super-c       spawn ${CALCULATOR}

# Focusing clients
hc keybind Super-h focus  left
hc keybind Super-j focus  down
hc keybind Super-k focus  up
hc keybind Super-l focus  right

# Moving clients
hc keybind Super-Shift-h  shift left
hc keybind Super-Shift-j  shift down
hc keybind Super-Shift-k  shift up
hc keybind Super-Shift-l  shift right

# Splitting frames
hc keybind Super-e  split explode
hc keybind Super-u  chain - split bottom 0.5 - focus bottom
hc keybind Super-o  chain - split right 0.5 - focus right

hc keybind Super-Shift-o chain \
    - split right 0.33 \
    - focus right \
    - split right 0.5

hc keybind Super-Shift-backslash chain \
    .-. focus_edge -e right \
    .-. split right 0.65 \
    .-. focus right

# Resizing frames
resizestep=0.02
hc keybind Super-comma   resize left +$resizestep
hc keybind Super-period  resize left -$resizestep
hc keybind Super-Alt-comma   resize right -$resizestep
hc keybind Super-Alt-period  resize right +$resizestep
hc keybind Super-equal   resize down +$resizestep
hc keybind Super-minus   resize up +$resizestep

# Tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

# use max layout on the default workspace which already existed before
# setting `default_frame_layout`
hc load default "(clients max:0)" || true
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "Super-$key" use_index "$i"
        hc keybind "Super-Shift-$key" move_index "$i"
    fi
done

# Cycle through tags
hc keybind Alt-Control-Down   use_index +1 --skip-visible
hc keybind Alt-Control-Up     use_index -1 --skip-visible
hc keybind Super-Control-Down use_index +1 --skip-visible
hc keybind Super-Control-Up   use_index -1 --skip-visible

# Layouting
hc keybind Super-Shift-p  pseudotile toggle
hc keybind Super-space    cycle_layout +1 vertical horizontal
hc keybind Super-s        floating toggle
hc keybind Super-0        fullscreen toggle
hc keybind Super-m        set_layout max
hc keybind Super-g        set_layout grid

hc keybind Super-bracketleft   rotate
hc keybind Super-bracketright  chain . lock . rotate . rotate . rotate . unlock

# Mouse
hc mousebind Super-Button1 move
hc mousebind Super-Button2 zoom
hc mousebind Super-Button3 resize

# Focus
hc keybind Super-Tab        cycle +1
hc keybind Super-Shift-Tab  cycle -1
hc keybind Alt-Tab          cycle_all +1
hc keybind Alt-Shift-Tab    cycle_all -1

#=======================================================================
# Rules
#=======================================================================

hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

#=======================================================================
# Panel
#=======================================================================

if [[ -f ~/.hdpi ]]; then
    export POLYBAR_HEIGHT=66
    export POLYBAR_DPI=192
else
    export POLYBAR_HEIGHT=33
    export POLYBAR_DPI=96
fi

pkill -u $USER 'polybar'
polybar 'top' &

#=======================================================================
# Finalize / Redraw all
#=======================================================================

hc unlock
